import type { AccountRole } from "@/lib/auth/roles";

export interface Profile {
  id: string;
  user_id: string;
  full_name: string;
  email: string;
  avatar_url?: string;
  /**
   * Legacy free-form role column from migration 001. Never read
   * by the app since 017_account_sharing.sql introduced the typed
   * `account_role` enum. Flagged for removal in a later cleanup
   * migration — kept on the type so existing destructures don't
   * break.
   */
  role: string;
  /**
   * Opted-in beta feature keys for this account. The column survives
   * for future beta gates; no current feature reads it (Flows was
   * the last user and went to soft-GA in PR #134). Defaults to `[]`
   * for every profile; toggled per-account via a direct UPDATE on
   * the `profiles` row.
   */
  beta_features?: string[];
  /**
   * Account this profile is a member of. Added by
   * `017_account_sharing.sql`; NOT NULL in the DB post-backfill.
   * Optional on the type only because older serialised payloads
   * (cached client state, test fixtures) may not have it yet.
   */
  account_id?: string;
  /**
   * Caller's role within their account. Source of truth for every
   * role-gated UI / API check — call `hasMinRole` from
   * `@/lib/auth/roles` rather than comparing this string directly.
   */
  account_role?: AccountRole;
  created_at: string;
}

// ============================================================
// Account-sharing entities (017_account_sharing.sql)
// ============================================================

export interface Account {
  id: string;
  name: string;
  /** auth.users.id of the immutable owner. */
  owner_user_id: string;
  created_at: string;
  updated_at: string;
}

/**
 * Hydrated member row for the Settings → Members tab. Combines
 * the profile and its account_role for a single member of the
 * caller's account. Sensitive fields (email) are populated only
 * when the caller has admin+ — agents and viewers see name +
 * avatar + role only.
 */
export interface AccountMember {
  user_id: string;
  full_name: string;
  email: string | null;
  avatar_url: string | null;
  role: AccountRole;
  joined_at: string;
}

/**
 * Outstanding invite link row. `token_hash` is intentionally
 * absent — it lives only in the DB and on the server. The
 * plaintext token is returned once at creation time and surfaced
 * via the invite URL; never re-emitted.
 */
export interface AccountInvitation {
  id: string;
  account_id: string;
  /** Roles offered via invite — owner is never offered. */
  role: Exclude<AccountRole, "owner">;
  created_by_user_id: string | null;
  label: string | null;
  created_at: string;
  expires_at: string;
  accepted_at: string | null;
  accepted_by_user_id: string | null;
}

export interface Contact {
  id: string;
  user_id: string;
  account_id: string;
  phone: string;
  /** Digits-only form of `phone`, generated by the DB (migration 022)
   *  and unique per account. Read-only. */
  phone_normalized?: string;
  name?: string;
  email?: string;
  company?: string;
  avatar_url?: string;
  blocked?: { id: string }[] | null;
  created_at: string;
  updated_at: string;
}

export interface Tag {
  id: string;
  user_id: string;
  name: string;
  color: string;
  created_at: string;
}

export interface ContactTag {
  id: string;
  contact_id: string;
  tag_id: string;
}

export interface CustomField {
  id: string;
  user_id: string;
  /** Tenancy key — NOT NULL since migration 017. */
  account_id: string;
  field_name: string;
  field_type: string;
  field_options?: Record<string, unknown>;
  created_at: string;
}

export interface ContactCustomValue {
  id: string;
  contact_id: string;
  custom_field_id: string;
  value?: string;
}

export interface ContactNote {
  id: string;
  contact_id: string;
  user_id: string;
  note_text: string;
  created_at: string;
}

export type ConversationStatus = 'open' | 'pending' | 'closed';

export interface Conversation {
  id: string;
  user_id: string;
  contact_id: string;
  status: ConversationStatus;
  deleted_at?: string | null;
  assigned_agent_id?: string;
  last_message_text?: string;
  last_message_at?: string;
  unread_count: number;
  created_at: string;
  updated_at: string;
  contact?: Contact;
  /**
   * AI agent mode (migration 023). When true, inbound text messages
   * are automatically answered by the configured AI provider.
   * Toggled from the Inbox UI or via the AI Agent dashboard.
   */
  ai_mode?: boolean;
  /**
   * Model override for this conversation (e.g. "openai/gpt-4o").
   * Falls back to the global AI_MODEL env var when null.
   */
  ai_model?: string | null;
  /**
   * System prompt override for this conversation.
   * Falls back to AI_SYSTEM_PROMPT env var / GENERIC_CRM_SYSTEM_PROMPT when null.
   */
  ai_system_prompt?: string | null;
  settings?: ConversationSettings | null;
  is_blocked?: boolean;
  blocked?: { id: string }[] | null;
  lead_conversations?: { lead: B2BLead }[] | null;
}

/**
 * Backward-compatible view type for the AI Agent dashboard.
 * Mirrors the shape returned by the ai_agent_conversations view
 * added in migration 023.
 */
export interface ConversationWithLastMessage extends Conversation {
  phone?: string;
  name?: string | null;
  last_message?: string | null;
  /** mode field from original Whatsapp-Agent-main: 'agent' | 'human' */
  mode?: 'agent' | 'human';
}

export type SenderType = 'customer' | 'agent' | 'bot';
export type ContentType =
  | 'text'
  | 'image'
  | 'document'
  | 'audio'
  | 'video'
  | 'location'
  | 'template'
  /** Customer tapped a reply button or list row on a message we sent. */
  | 'interactive';
export type MessageStatus = 'sending' | 'sent' | 'delivered' | 'read' | 'failed';

export interface Message {
  id: string;
  conversation_id: string;
  sender_type: SenderType;
  sender_id?: string;
  content_type: ContentType;
  content_text?: string;
  media_url?: string;
  template_name?: string;
  message_id?: string;
  status: MessageStatus;
  created_at: string;
  reply_to_message_id?: string;
  /**
   * Only set when `content_type === 'interactive'` — the stable id of
   * the button or list row the customer tapped. The Flows engine uses
   * this to route the next node; the inbox bubble uses it as a styling
   * cue (renders with a "↩ button reply" affordance).
   */
  interactive_reply_id?: string;
}

export type ReactionActor = 'customer' | 'agent';

export interface MessageReaction {
  id: string;
  message_id: string;
  conversation_id: string;
  actor_type: ReactionActor;
  actor_id?: string;
  emoji: string;
  created_at: string;
}

export interface WhatsAppConfig {
  id: string;
  user_id: string;
  phone_number_id: string;
  waba_id?: string;
  access_token: string;
  verify_token?: string;
  status: 'connected' | 'disconnected';
  connected_at?: string;
  /**
   * Set when POST /{phone_number_id}/register last succeeded. NULL
   * means the number was saved but never actually subscribed for
   * webhooks on Meta's side — inbound events will be silently lost.
   */
  registered_at?: string;
  /** Set when POST /{waba_id}/subscribed_apps last succeeded. */
  subscribed_apps_at?: string;
  /** Last error from /register; cleared on success. */
  last_registration_error?: string;
  ai_enabled?: boolean;
  ai_only_free_models?: boolean;
  ai_model?: string;
  ai_system_prompt?: string;
  app_secret?: string;
  openrouter_api_key?: string;
}

// Raw Meta status enum. We persist this verbatim from Meta (sync + webhook)
// rather than collapsing to a local TitleCase set — distinctions like
// PAUSED vs DISABLED vs IN_APPEAL drive the edit/resubmit/delete flows.
// DRAFT is the local-only state before the row is submitted to Meta.
export type MessageTemplateStatus =
  | 'DRAFT'
  | 'PENDING'
  | 'APPROVED'
  | 'REJECTED'
  | 'PAUSED'
  | 'DISABLED'
  | 'IN_APPEAL'
  | 'PENDING_DELETION';

export type TemplateButton =
  | { type: 'QUICK_REPLY'; text: string }
  | { type: 'URL'; text: string; url: string; example?: string }
  | { type: 'PHONE_NUMBER'; text: string; phone_number: string }
  | { type: 'COPY_CODE'; text: string; example: string };

export interface TemplateSampleValues {
  body?: string[];
  header?: string[];
}

export interface MessageTemplate {
  id: string;
  user_id: string;
  name: string;
  category: 'Marketing' | 'Utility' | 'Authentication';
  language?: string;
  header_type?: 'text' | 'image' | 'video' | 'document';
  header_content?: string;
  header_handle?: string;
  header_media_url?: string;
  body_text: string;
  footer_text?: string;
  buttons?: TemplateButton[];
  sample_values?: TemplateSampleValues;
  status?: MessageTemplateStatus;
  meta_template_id?: string;
  rejection_reason?: string;
  quality_score?: 'GREEN' | 'YELLOW' | 'RED';
  submission_error?: string;
  last_submitted_at?: string;
  created_at: string;
}

export interface Pipeline {
  id: string;
  user_id: string;
  name: string;
  created_at: string;
}

export interface PipelineStage {
  id: string;
  pipeline_id: string;
  name: string;
  position: number;
  color: string;
  created_at: string;
}

export type DealStatus = 'open' | 'won' | 'lost';

export interface Deal {
  id: string;
  user_id: string;
  pipeline_id: string;
  stage_id: string;
  /**
   * Nullable after migration 004 — becomes NULL when the referenced
   * contact is deleted (ON DELETE SET NULL). History preserved.
   */
  contact_id: string | null;
  conversation_id?: string;
  assigned_to?: string;
  title: string;
  value: number;
  currency?: string;
  notes?: string;
  expected_close_date?: string;
  status?: DealStatus;
  created_at: string;
  updated_at?: string;
  contact?: Contact;
  stage?: PipelineStage;
  assignee?: Profile;
}

export type BroadcastStatus = 'draft' | 'scheduled' | 'sending' | 'sent' | 'failed';
export type RecipientStatus = 'pending' | 'sent' | 'delivered' | 'read' | 'replied' | 'failed';

export interface Broadcast {
  id: string;
  user_id: string;
  name: string;
  template_name: string;
  template_language: string;
  template_variables?: Record<string, unknown>;
  audience_filter?: Record<string, unknown>;
  scheduled_at?: string;
  status: BroadcastStatus;
  total_recipients: number;
  sent_count: number;
  delivered_count: number;
  read_count: number;
  replied_count: number;
  failed_count: number;
  created_at: string;
}

export interface BroadcastRecipient {
  id: string;
  broadcast_id: string;
  /**
   * Nullable after migration 004 — becomes NULL when the referenced
   * contact is deleted (ON DELETE SET NULL). History preserved; the
   * UI renders "Unknown" for orphaned rows.
   */
  contact_id: string | null;
  status: RecipientStatus;
  sent_at?: string;
  delivered_at?: string;
  read_at?: string;
  replied_at?: string;
  error_message?: string;
  /**
   * Meta's message id, persisted when the broadcast send succeeds so
   * the webhook can mirror status updates back onto the recipient row.
   * Added in migration 003.
   */
  whatsapp_message_id?: string;
  created_at: string;
  contact?: Contact;
}

// ============================================================
// Automations (migration 006)
// ============================================================

export type AutomationTriggerType =
  | 'new_message_received'
  | 'first_inbound_message'
  | 'keyword_match'
  | 'new_contact_created'
  | 'conversation_assigned'
  | 'tag_added'
  | 'time_based';

export type AutomationStepType =
  | 'send_message'
  | 'send_template'
  | 'add_tag'
  | 'remove_tag'
  | 'assign_conversation'
  | 'update_contact_field'
  | 'create_deal'
  | 'wait'
  | 'condition'
  | 'send_webhook'
  | 'close_conversation';

export type AutomationLogStatus = 'success' | 'partial' | 'failed';

export interface KeywordMatchTriggerConfig {
  keywords: string[];
  match_type: 'exact' | 'contains';
  case_sensitive?: boolean;
}

export interface TagTriggerConfig {
  tag_id: string;
}

export interface TimeBasedTriggerConfig {
  /** Cron expression or simple HH:mm string; engine can accept either. */
  schedule: string;
  timezone?: string;
}

export type AutomationTriggerConfig =
  | Record<string, never>
  | KeywordMatchTriggerConfig
  | TagTriggerConfig
  | TimeBasedTriggerConfig
  | Record<string, unknown>;

export interface SendMessageStepConfig {
  text: string;
}

export interface SendTemplateStepConfig {
  template_name: string;
  language?: string;
  variables?: Record<string, string>;
}

export interface TagStepConfig {
  tag_id: string;
}

export interface AssignConversationStepConfig {
  mode: 'specific' | 'round_robin';
  agent_id?: string;
}

export interface UpdateContactFieldStepConfig {
  /**
   * Either a built-in contact column (`name` | `email` | `company`) or a
   * custom field encoded as `custom:<custom_field_id>`. The `custom:` prefix
   * is how the engine distinguishes a `contact_custom_values` write from a
   * direct `contacts` column update. Older configs store the bare column name,
   * so this stays backward compatible.
   */
  field: string;
  /** Supports `{{ vars.* }}` / `{{ message.text }}` interpolation at runtime. */
  value: string;
}

export interface CreateDealStepConfig {
  pipeline_id: string;
  stage_id: string;
  title: string;
  value?: number;
}

export interface WaitStepConfig {
  amount: number;
  unit: 'minutes' | 'hours' | 'days';
}

export type ConditionSubject =
  | 'contact_field'
  | 'tag_presence'
  | 'message_content'
  | 'time_of_day';

export interface ConditionStepConfig {
  subject: ConditionSubject;
  /** e.g. field name, tag id, substring, or "HH:mm-HH:mm" depending on subject */
  operand?: string;
  /** For contact_field equals / message_content contains — comparison value */
  value?: string;
}

export interface SendWebhookStepConfig {
  url: string;
  headers?: Record<string, string>;
  body_template?: string;
}

export type AutomationStepConfig =
  | SendMessageStepConfig
  | SendTemplateStepConfig
  | TagStepConfig
  | AssignConversationStepConfig
  | UpdateContactFieldStepConfig
  | CreateDealStepConfig
  | WaitStepConfig
  | ConditionStepConfig
  | SendWebhookStepConfig
  | Record<string, never>
  | Record<string, unknown>;

export interface Automation {
  id: string;
  /** Account tenancy key — every automation belongs to one account
   *  (migration 017 made the column NOT NULL). The engine looks up
   *  active automations by this field on inbound webhook events. */
  account_id: string;
  /** Original author. Used for log audit + outbound message
   *  sender-of-record, never for tenancy isolation. */
  user_id: string;
  name: string;
  description?: string;
  trigger_type: AutomationTriggerType;
  trigger_config: AutomationTriggerConfig;
  is_active: boolean;
  execution_count: number;
  last_executed_at?: string | null;
  created_at: string;
  updated_at: string;
}

export interface AutomationStep {
  id: string;
  automation_id: string;
  parent_step_id?: string | null;
  branch?: 'yes' | 'no' | null;
  step_type: AutomationStepType;
  step_config: AutomationStepConfig;
  position: number;
  created_at: string;
}

export interface AutomationLogStepResult {
  step_id: string;
  step_type: AutomationStepType;
  status: 'success' | 'skipped' | 'failed';
  detail?: string;
}

export interface AutomationLog {
  id: string;
  automation_id: string;
  user_id: string;
  contact_id: string | null;
  trigger_event: string;
  steps_executed: AutomationLogStepResult[];
  status: AutomationLogStatus;
  error_message?: string | null;
  created_at: string;
  contact?: Contact;
}

// ============================================================
// B2B Marketplace Integrations (migration 026)
// ============================================================

export type B2BPlatform = 'INDIAMART' | 'TRADEINDIA' | 'EXPORTERSINDIA' | 'ALIBABA';
export type B2BSyncInterval = '5m' | '15m' | '30m' | '1h';
export type B2BLeadStatus = 'pending' | 'assigned' | 'contacted' | 'converted' | 'rejected';

export interface B2BIntegration {
  id: string;
  account_id: string;
  platform: B2BPlatform;
  enabled: boolean;
  api_url?: string | null;
  api_key?: string | null;
  client_id?: string | null;
  client_secret?: string | null;
  username?: string | null;
  password?: string | null;
  sync_interval: B2BSyncInterval;
  last_sync_at?: string | null;
  created_at: string;
  updated_at: string;
}

export interface B2BLead {
  id: string;
  account_id: string;
  platform: B2BPlatform;
  external_lead_id: string;
  buyer_name?: string | null;
  company_name?: string | null;
  mobile?: string | null;
  alternate_mobile?: string | null;
  email?: string | null;
  city?: string | null;
  state?: string | null;
  country?: string | null;
  product_name?: string | null;
  quantity?: string | null;
  message?: string | null;
  status: B2BLeadStatus;
  lead_source: string;
  lead_score?: number | null;
  assigned_to?: string | null;
  received_at: string;
  inquiry_at?: string | null;
  created_at: string;
  updated_at: string;
  notes?: string | null;
  /** Soft-delete timestamp — NULL means the lead is active (migration 027). */
  deleted_at?: string | null;
  assignee?: Profile;
}


export interface B2BRawLog {
  id: string;
  account_id: string;
  platform: B2BPlatform;
  payload_json: unknown;
  created_at: string;
}

export interface NotificationRecipient {
  id: string;
  account_id: string;
  name: string;
  mobile: string;
  enabled: boolean;
  created_at: string;
  updated_at: string;
}

export interface LeadAssignment {
  id: string;
  account_id: string;
  lead_id: string;
  staff_id: string;
  assigned_at: string;
}

export interface IntegrationSyncState {
  id: string;
  account_id: string;
  platform: B2BPlatform;
  last_sync_at?: string | null;
  last_successful_sync?: string | null;
  last_lead_timestamp?: string | null;
  current_page: number;
  retry_count: number;
  sync_status: 'IDLE' | 'RUNNING' | 'COMPLETED' | 'FAILED';
  error_message?: string | null;
  created_at: string;
  updated_at: string;
  current_date_filter?: string | null;
  custom_start_date?: string | null;
  custom_end_date?: string | null;
  current_cursor?: string | null;
  last_lead_id?: string | null;
}

export interface SyncLog {
  id: string;
  account_id: string;
  platform: B2BPlatform;
  started_at: string;
  finished_at?: string | null;
  records_imported: number;
  status: 'SUCCESS' | 'FAILED' | 'RUNNING';
  error_message?: string | null;
  duration?: number | null;
  created_at: string;
}

export interface ConversationSettings {
  id: string;
  conversation_id: string;
  is_pinned: boolean;
  is_starred: boolean;
  is_archived: boolean;
  is_muted: boolean;
  ai_replies_enabled: boolean;
  notification_preferences: Record<string, unknown>;
  created_at: string;
  updated_at: string;
}

export interface BlockedContact {
  id: string;
  account_id: string;
  contact_id: string;
  blocked_by?: string | null;
  reason?: string | null;
  created_at: string;
}

export interface ChatNote {
  id: string;
  conversation_id: string;
  user_id: string;
  note_text: string;
  is_pinned: boolean;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
}

export interface MessageAuditLog {
  id: string;
  message_id: string;
  user_id?: string | null;
  action: string;
  metadata?: Record<string, unknown> | null;
  created_at: string;
}

export interface ConversationAuditLog {
  id: string;
  conversation_id: string;
  user_id?: string | null;
  action: string;
  old_value?: string | null;
  new_value?: string | null;
  created_at: string;
}

// ============================================================
// Quotation Module
// ============================================================

export type QuotationStatus = 'draft' | 'sent' | 'accepted' | 'rejected' | 'expired' | 'cancelled';

export type ProformaStatus = 'draft' | 'issued' | 'waiting_payment' | 'partially_paid' | 'paid' | 'cancelled';

export type SalesRegisterStatus = 'pending' | 'processing' | 'completed' | 'cancelled' | 'delivered';

export type QuotationTaxType =
  | 'none'
  | 'gst_18' | 'gst_12' | 'gst_5'
  | 'igst_18' | 'igst_12' | 'igst_5'
  | 'cgst_sgst_18' | 'cgst_sgst_12' | 'cgst_sgst_5'
  | 'custom';

export interface QuotationItem {
  id: string;
  quotation_id: string;
  position: number;
  product_name: string;
  description?: string | null;
  hsn_code?: string | null;
  uom: string;
  rate: number;
  quantity: number;
  /** generated column — rate × quantity */
  amount: number;
  image_url?: string | null;
  created_at: string;
}

export interface QuotationTerm {
  id: string;
  quotation_id: string;
  terms_text: string;
  updated_at: string;
}

export interface QuotationLog {
  id: string;
  quotation_id: string;
  channel: 'whatsapp' | 'email' | 'sms';
  recipient?: string | null;
  status: string;
  message_id?: string | null;
  error?: string | null;
  sent_by?: string | null;
  sent_at: string;
}

export interface Quotation {
  id: string;
  account_id: string;
  quotation_no: string;
  entry_date: string;           // ISO date string "YYYY-MM-DD"
  company_name: string;
  kind_attention?: string | null;
  contact_person?: string | null;
  email?: string | null;
  mobile: string;
  alt_mobile?: string | null;
  address: string;
  city?: string | null;
  state?: string | null;
  pincode?: string | null;
  country?: string | null;
  gst_no?: string | null;
  source?: string | null;
  subject?: string | null;
  basic_total: number;
  tax_type: QuotationTaxType;
  custom_tax_rate?: number | null;
  tax_amount: number;
  grand_total: number;
  amount_words?: string | null;
  status: QuotationStatus;
  bank_account_name?: string | null;
  bank_account_type?: string | null;
  bank_account_number?: string | null;
  bank_name?: string | null;
  bank_ifsc?: string | null;
  manager_name?: string | null;
  manager_designation?: string | null;
  lead_id?: string | null;
  valid_until?: string | null;
  created_by?: string | null;
  updated_by?: string | null;
  deleted_at?: string | null;
  created_at: string;
  updated_at: string;
  // hydrated relations (optional)
  company_details?: {
    logo_url?: string | null;
    company_name?: string | null;
    tagline?: string | null;
    address?: string | null;
    city?: string | null;
    state?: string | null;
    country?: string | null;
    pincode?: string | null;
    phone?: string | null;
    alternate_phone?: string | null;
    email?: string | null;
    website?: string | null;
    gst_number?: string | null;
    // Bank details
    bank_account_name?: string | null;
    bank_account_type?: string | null;
    bank_account_number?: string | null;
    bank_name?: string | null;
    bank_ifsc?: string | null;
    // Quotation-specific
    manager_name?: string | null;
    manager_designation?: string | null;
    signature_url?: string | null;
    quotation_terms_text?: string | null;
    proforma_terms_text?: string | null;
    sales_register_terms_text?: string | null;
    terms_and_conditions?: string | null;
    contact_numbers?: string | null;
    email_details?: string | null;
    jurisdiction?: string | null;
    footer_text?: string | null;
    seal_url?: string | null;
    logo_alignment?: string | null;
  } | null;
  company_logo_url?: string | null;
  items?: QuotationItem[];
  terms?: QuotationTerm | null;
  logs?: QuotationLog[];
  creator?: Pick<Profile, 'id' | 'full_name' | 'avatar_url'> | null;
  lead?: {
    id: string;
    buyer_name: string | null;
    company_name: string | null;
    platform: string;
  } | null;
  proforma?: Proforma | null;
}

export interface ProformaItem {
  id: string;
  proforma_id: string;
  position: number;
  product_name: string;
  description?: string | null;
  hsn_code?: string | null;
  uom: string;
  rate: number;
  quantity: number;
  amount: number;
  image_url?: string | null;
  created_at: string;
}

export interface ProformaTerm {
  id: string;
  proforma_id: string;
  terms_text: string;
  updated_at: string;
}

export interface ProformaLog {
  id: string;
  proforma_id: string;
  channel: 'whatsapp' | 'email' | 'sms';
  recipient?: string | null;
  status: string;
  message_id?: string | null;
  error?: string | null;
  sent_by?: string | null;
  sent_at: string;
}

export interface Proforma {
  id: string;
  account_id: string;
  proforma_no: string;
  parent_quotation_id?: string | null;
  entry_date: string;
  company_name: string;
  kind_attention?: string | null;
  contact_person?: string | null;
  email?: string | null;
  mobile: string;
  alt_mobile?: string | null;
  address: string;
  city?: string | null;
  state?: string | null;
  pincode?: string | null;
  country?: string | null;
  gst_no?: string | null;
  source?: string | null;
  subject?: string | null;
  basic_total: number;
  tax_type: QuotationTaxType;
  custom_tax_rate?: number | null;
  tax_amount: number;
  grand_total: number;
  amount_words?: string | null;
  status: ProformaStatus;
  bank_account_name?: string | null;
  bank_account_type?: string | null;
  bank_account_number?: string | null;
  bank_name?: string | null;
  bank_ifsc?: string | null;
  manager_name?: string | null;
  manager_designation?: string | null;
  lead_id?: string | null;
  valid_until?: string | null;
  transportation_charges?: number;
  packing_charges?: number;
  other_charges?: number;
  reference_number?: string | null;
  notes?: string | null;
  approval_status?: string;
  conversion_history?: any[] | null;
  document_type?: string | null;
  document_relationships?: any[] | null;
  audit_history?: any[] | null;
  created_by?: string | null;
  updated_by?: string | null;
  deleted_at?: string | null;
  created_at: string;
  updated_at: string;
  // hydrated relations
  company_details?: Quotation['company_details'];
  company_logo_url?: string | null;
  items?: ProformaItem[];
  terms?: ProformaTerm | null;
  logs?: ProformaLog[];
  creator?: Quotation['creator'];
  lead?: Quotation['lead'];
  parent_quotation?: Quotation | null;
  sales_register?: SalesRegister | null;
}

export interface SalesRegisterItem {
  id: string;
  sales_register_id: string;
  position: number;
  product_name: string;
  description?: string | null;
  hsn_code?: string | null;
  uom: string;
  rate: number;
  quantity: number;
  amount: number;
  image_url?: string | null;
  created_at: string;
}

export interface SalesRegisterTerm {
  id: string;
  sales_register_id: string;
  terms_text: string;
  updated_at: string;
}

export interface SalesRegisterLog {
  id: string;
  sales_register_id: string;
  channel: 'whatsapp' | 'email' | 'sms';
  recipient?: string | null;
  status: string;
  message_id?: string | null;
  error?: string | null;
  sent_by?: string | null;
  sent_at: string;
}

export interface SalesRegister {
  id: string;
  account_id: string;
  sales_register_no: string;
  parent_proforma_id?: string | null;
  entry_date: string;
  company_name: string;
  kind_attention?: string | null;
  contact_person?: string | null;
  email?: string | null;
  mobile: string;
  alt_mobile?: string | null;
  address: string;
  city?: string | null;
  state?: string | null;
  pincode?: string | null;
  country?: string | null;
  gst_no?: string | null;
  source?: string | null;
  subject?: string | null;
  basic_total: number;
  tax_type: QuotationTaxType;
  custom_tax_rate?: number | null;
  tax_amount: number;
  grand_total: number;
  amount_words?: string | null;
  status: SalesRegisterStatus;
  bank_account_name?: string | null;
  bank_account_type?: string | null;
  bank_account_number?: string | null;
  bank_name?: string | null;
  bank_ifsc?: string | null;
  manager_name?: string | null;
  manager_designation?: string | null;
  lead_id?: string | null;
  valid_until?: string | null;
  dispatch_courier?: string | null;
  dispatch_tracking_no?: string | null;
  dispatch_date?: string | null;
  transportation_charges?: number;
  packing_charges?: number;
  other_charges?: number;
  reference_number?: string | null;
  notes?: string | null;
  approval_status?: string;
  conversion_history?: any[] | null;
  document_type?: string | null;
  document_relationships?: any[] | null;
  audit_history?: any[] | null;
  created_by?: string | null;
  updated_by?: string | null;
  deleted_at?: string | null;
  created_at: string;
  updated_at: string;
  // hydrated relations
  company_details?: Quotation['company_details'];
  company_logo_url?: string | null;
  items?: SalesRegisterItem[];
  terms?: SalesRegisterTerm | null;
  logs?: SalesRegisterLog[];
  creator?: Quotation['creator'];
  lead?: Quotation['lead'];
  parent_proforma?: Proforma | null;
}

export interface CompanyBankAccount {
  id: string;
  account_id: string;
  account_name: string;
  account_type: string;
  account_number: string;
  bank_name: string;
  bank_ifsc: string;
  branch_name?: string | null;
  swift_code?: string | null;
  upi_id?: string | null;
  is_default: boolean;
  created_at?: string;
  updated_at?: string;
}

// ============================================================
// CRM Role & Permission System (Migration 030 + 033)
// ============================================================

/** The three canonical CRM roles. */
export type CrmRole = 'Super Admin' | 'Admin' | 'Sales';

/** All granular permission modules available in the system. */
export type CrmPermissionModule =
  | 'dashboard'
  | 'enquiries'
  | 'quotation'
  | 'proforma'
  | 'sales'
  | 'inbox'
  | 'contacts'
  | 'reports'
  | 'automations'
  | 'broadcasts'
  | 'crm_pipeline'
  | 'user_management'
  | 'settings'
  | 'integrations'
  | 'company_settings'
  | 'whatsapp_settings'
  | 'ai_settings'
  | 'indiamart_settings'
  | 'tradeindia_settings'
  | 'exportersindia_settings'
  | 'smtp_settings'
  | 'audit_logs'
  | 'role_management'
  // Legacy modules (kept for backward compat)
  | 'leads'
  | 'customers'
  | 'whatsapp'
  | 'indiamart'
  | 'tradeindia'
  | 'exportersindia'
  | 'crm'
  | 'analytics'
  | 'notifications'
  | 'ai_assistant';

export interface CrmPermission {
  id: string;
  module: CrmPermissionModule;
  action: string;
  description?: string;
}

/** Direct per-user permission grant (table: user_permissions). */
export interface UserPermission {
  id: string;
  user_id: string;
  permission_id: string;
  granted_by?: string | null;
  granted_at: string;
  permission?: CrmPermission;
}

/**
 * Module display labels used in UI (sidebar, user creation checkboxes).
 * Maps the new module name → user-facing label.
 */
export const MODULE_LABELS: Record<string, string> = {
  dashboard:           'Dashboard',
  enquiries:           'Enquiries',
  quotation:           'Quotation Register',
  proforma:            'Proforma Invoice',
  sales:               'Sales Register',
  inbox:               'Inbox',
  contacts:            'Contacts',
  reports:             'Reports',
  automations:         'Automations',
  broadcasts:          'Broadcasts',
  crm_pipeline:        'CRM Pipeline',
  user_management:     'User Management',
  settings:            'Settings',
  integrations:        'Integrations',
  company_settings:    'Company Settings',
  whatsapp_settings:   'WhatsApp Settings',
  ai_settings:         'AI Settings',
  indiamart_settings:  'IndiaMART Settings',
  tradeindia_settings: 'TradeIndia Settings',
  exportersindia_settings: 'ExportersIndia Settings',
  smtp_settings:       'SMTP Settings',
  audit_logs:          'Audit Logs',
  role_management:     'Roles & Permissions',
};

